FROM python:3.11-slim

# 작업 디렉토리
WORKDIR /app

# 시스템 패키지
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY docker/requirements_streamlit.txt app/requirements_streamlit.txt

RUN pip install --no-cache-dir -r app/requirements_streamlit.txt

# 애플리케이션 코드 복사
COPY admin/ /app

# Streamlit 포트
EXPOSE 8501

# 실행 명령
CMD ["streamlit", "run", "app.py"]
